# Site settings
title:          Logcat
description:    "blog for logcat group"
baseurl:        "/effective-java"
url:            "https://programming-book-reading-group.github.io"

# Author
author:
  name:         logcat
  url:          https://irlogcat.ir
  email:        info@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed
paginate:       5

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title


# Exclude files
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
